### ISSUE TITLE
DUB Package

### ISSUE THREAD

**Issue by anton-dutov** [MGWL/QtE5#1]
Здравствуйте, отличная идея.
Для языка D есть система сборки (http://code.dlang.org/getting_started) аналог make, и каталог пакетов http://code.dlang.org/ - думаю если вы оформите в виде пакета, это привлечет больше заинтересованых людей, и еще больше упростит использование.
Как я понял у Вас не очень хорошо с английским, если будут проблеммы с пониманием документации, могу помочь.

**Comment by MGWL** [comment]
Спасибо за предложение. Посмотрю обязательно!
