### ISSUE TITLE
Release on Dub 

### ISSUE THREAD

**Issue by aberba** [MGWL/QtE5#10]
Hello Gennady, I'm very happy you're working on this Qt binding. The version in D's package repository has not been updated for a while. Wanted to know why.

**Comment by MGWL** [comment]
There is not enough opportunity to override LD_LIBRARY_PATH for automatic creation through dub utility.

**Comment by Superbelko** [comment]
Um, this is per process variable, also you know those "true linux gurus" will yell at you "TiS is NoT canonical waY!11 U ShouLd InStall yOur LibS" so I don't see problem here. 

App authors should decide for themselves if they want it this way or do a global install, or just set it prior to launch in console.
