### ISSUE TITLE
Error load: QtE5WebEng32.so on Windows 10 32-bit

### ISSUE THREAD

**Issue by MassMessage** [MGWL/QtE5#5]
When I try compile webview.d from examples folder on Windows 10 32-bit I got this error:

> Error load: QtE5WebEng32.so

since .so are UNIX and I'm on Windows, I assued this was just filename's extension typo for .dll extension but I couldn't such dll even when using:

> windeployqt --webkit2 --release myQtApp.exe

**Comment by MGWL** [comment]
Prior to version Qt-5.5, WebKit was used, and for later versions of chromium-based WebEngine. You probably have a WebKit-based version and need to use:
Loader(dll.Qt5widgets + dll.QtE5Web, true)). 
LoadQt (...)  for Windows 32/64 WebEngine contains a typo ... Must be DLL

**Comment by MassMessage** [comment]
Where is Loader() defined? I'm getting error: undefined identifier Loader, did you mean function LoadQt?

**Comment by MGWL** [comment]
Sorry, not Loader() but LoadQt

Again on Qt.

Qt5 under Windows can be built by either mingw or MSVC studio.
 I don't work with MSVC studio, I didn't build WebEngine for Windows, just checked WebEngine only on Linux
(hence the confusion with dll / so in LoadQt)

For Windows, I checked only WebKit.
