### ISSUE TITLE
Where can I download?

### ISSUE THREAD

**Issue by enjoysmath** [MGWL/QtE5#6]
There's no instructions on how to install the thing for use as a library in my code.

...

**Comment by MGWL** [comment]
Windows:
1 - create new folder ... test
2 - Copy all files from rtl_qt5_32 in test
3 - Copy windows32\QtE5Widgets32.dll  in test
4 - Copy all files from source to test
5 - Copy examples\hello.d to test
6 - go in test
7 - dmd hello qte5
8 - run hello.exe

**Comment by MGWL** [comment]
example build hello on win32
